"""Focused technical QA for the bounded Tier 1 discovery sidecars."""

from __future__ import annotations

import gzip
import json
import re
import tempfile
import unittest
from collections import defaultdict
from pathlib import Path
import sys

MODULE_DIR = Path(__file__).resolve().parents[1] / "scripts" / "exploration" / "model_observability"
sys.path.insert(0, str(MODULE_DIR))

import build_domestic_model_context_sample as sampler
import apply_domestic_discovery_annotations as annotations
import offline_signal_scanner as scanner
import scan_domestic_model_keywords as keyword_scan
from domestic_discovery_common import (
    context_cue,
    iter_first_messages,
    limited_context,
    load_json,
    match_location,
    normalize_discovery_text,
)


ROOT = MODULE_DIR
BASELINE_IDS = {
    "m0_deepseek_name",
    "m0_qwen_model_name",
    "m0_kimi_model_name",
    "m0_glm_model_name",
    "h1_qwen_code_coauthor_trailer",
}


class CommonTests(unittest.TestCase):
    def test_first_record_dedup_and_stats(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "records.jsonl.gz"
            rows = [envelope("r1:s1", "first"), envelope("r1:s1", "second"), envelope("r2:s2", "third")]
            with gzip.open(path, "wt", encoding="utf-8") as handle:
                for row in rows:
                    handle.write(json.dumps(row) + "\n")
            stats = defaultdict(int)
            found = list(iter_first_messages("matched_10min", {"r1:s1", "r2:s2"}, [path], stats))
            self.assertEqual([row.message for row in found], ["first", "third"])
            self.assertEqual(stats["duplicate_population_source_records"], 1)
            self.assertEqual(stats["unmapped_repository_sha"], 0)

    def test_redacted_limited_context(self) -> None:
        text = "subject\nGenerated by DeepSeek <person@example.com> HTTPS://example.com/u @person abcdef1234567890"
        start = text.index("DeepSeek")
        excerpt = limited_context(text, start, start + 8)
        self.assertIn("DeepSeek", excerpt)
        self.assertNotIn("person@example.com", excerpt)
        self.assertNotIn("example.com", excerpt)
        self.assertNotIn("@person", excerpt)

    def test_location_and_cues(self) -> None:
        text = "subject\nbody\nCo-authored-by: Qwen-Coder <x@y.z>"
        start = text.index("Qwen")
        self.assertEqual(match_location(text, start), ("trailer", 2))
        self.assertEqual(context_cue(text), "attribution_cue")
        self.assertEqual(normalize_discovery_text("Ｑｗｅｎ"), "Qwen")


class BaselineTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        registry = load_json(ROOT / "SIGNATURE_REGISTRY.v1.1.0.json")
        cls.patterns = {
            row["signal_id"]: (row, regex)
            for row, regex in scanner.compile_registry(registry)
            if row["signal_id"] in BASELINE_IDS
        }

    def count(self, signal_id: str, message: str) -> int:
        row, regex = self.patterns[signal_id]
        return len(list(scanner.match_values(row, regex, message)))

    def test_sealed_patterns_are_loaded_verbatim(self) -> None:
        registry = load_json(ROOT / "SIGNATURE_REGISTRY.v1.1.0.json")
        raw = {row["signal_id"]: row["pattern"] for row in registry["patterns"]}
        compiled = {key: row["pattern"] for key, (row, _) in self.patterns.items()}
        self.assertEqual(compiled, {key: raw[key] for key in BASELINE_IDS})

    def test_qwen_and_kimi_harness_exclusions(self) -> None:
        self.assertEqual(self.count("m0_qwen_model_name", "Qwen Code"), 0)
        self.assertEqual(self.count("m0_qwen_model_name", "Qwen2.5"), 1)
        self.assertEqual(self.count("m0_kimi_model_name", "Kimi Code"), 0)
        self.assertEqual(self.count("m0_kimi_model_name", "Kimi K2"), 1)

    def test_h1_multiline_exactness(self) -> None:
        good = "subject\n\nCo-authored-by: Qwen-Coder <qwen-coder@alibabacloud.com>"
        bad = "subject\nCo-authored-by: Qwen Coder <qwen-coder@alibabacloud.com>"
        self.assertEqual(self.count("h1_qwen_code_coauthor_trailer", good), 1)
        self.assertEqual(self.count("h1_qwen_code_coauthor_trailer", bad), 0)


class LexiconTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.lexicon = load_json(ROOT / "DOMESTIC_MODEL_DISCOVERY_LEXICON.v0.1.json")

    def test_unique_ids_and_compilable_regexes(self) -> None:
        patterns = self.lexicon["patterns"]
        ids = [row["pattern_id"] for row in patterns]
        self.assertEqual(len(ids), len(set(ids)))
        for row in patterns:
            re.compile(row["regex"])

    def test_only_tier1_families_and_discovery_ceilings(self) -> None:
        allowed = {"deepseek", "qwen", "kimi", "glm", "doubao_seed_trae"}
        self.assertEqual({row["family_id"] for row in self.lexicon["patterns"]}, allowed)
        self.assertLessEqual({row["evidence_ceiling"] for row in self.lexicon["patterns"]}, {"H0", "M0"})

    def test_alias_examples(self) -> None:
        patterns = [(row["pattern_id"], re.compile(row["regex"])) for row in self.lexicon["patterns"]]
        samples = ["deepseek_coder_v2", "Qwen2.5-Coder", "Kimi Code", "ChatGLM-4", "CodeGeeX", "Seed-Coder", "TRAE Agent"]
        for sample in samples:
            self.assertTrue(any(regex.search(sample) for _, regex in patterns), sample)


class SamplingTests(unittest.TestCase):
    def test_cap_and_determinism(self) -> None:
        rows = sampler.add_strata([candidate(index) for index in range(300)])
        first = sampler.deterministic_select(rows, "seed", 240)
        second = sampler.deterministic_select(rows, "seed", 240)
        self.assertEqual(len(first), 240)
        self.assertEqual([row["repo_sha_key"] for row in first], [row["repo_sha_key"] for row in second])
        self.assertEqual(len({row["repo_sha_key"] for row in first}), 240)

    def test_absolute_cap_guard(self) -> None:
        rows = sampler.add_strata([candidate(index) for index in range(250)])
        with self.assertRaises(ValueError):
            sampler.deterministic_select(rows, "seed", 241)

    def test_annotation_map_is_complete_and_bounded(self) -> None:
        mapping = annotations.annotation_map(240)
        self.assertEqual(set(mapping), set(range(1, 241)))
        self.assertEqual(len(mapping), 240)
        self.assertLessEqual(set(mapping.values()), set(annotations.RATIONALES))

    def test_annotation_rejects_nonfrozen_sample(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "DOMESTIC_MODEL_DISCOVERY_SAMPLE.csv"
            path.write_text("selection_rank\n1\n", encoding="utf-8")
            with self.assertRaisesRegex(RuntimeError, "valid only for the frozen sample"):
                annotations.verify_frozen_sample(path)

    def test_baseline_gate_requires_explicit_closed_record(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "closure.json"
            with self.assertRaisesRegex(RuntimeError, "closure is missing"):
                keyword_scan.assert_baseline_gate(path)
            path.write_text(json.dumps({
                "status": "closed",
                "input_hash_verification": "passed",
            }), encoding="utf-8")
            self.assertEqual(keyword_scan.assert_baseline_gate(path)["status"], "closed")


def envelope(repo_sha: str, message: str) -> dict[str, object]:
    return {
        "repo_sha": repo_sha,
        "agent": "codex",
        "channel": "test",
        "item": {"commit": {"message": message, "author": {"date": "2026-01-01T00:00:00Z"}}},
    }


def candidate(index: int) -> dict[str, str]:
    families = ["deepseek", "qwen", "kimi", "glm", "doubao_seed_trae"]
    return {
        "branch": "matched_10min" if index % 2 == 0 else "supplementary_4h",
        "repo_sha_key": f"key-{index}",
        "family_id": families[index % len(families)],
        "pattern_ids": "p",
        "entity_types": "model",
        "raw_occurrences": "1",
        "location": ["subject", "body", "trailer"][index % 3],
        "author_month": f"2026-{(index % 12) + 1:02d}",
        "context_cue": ["no_cue", "attribution_cue", "structured_cue"][index % 3],
        "template_key": f"template-{index % 30}",
        "limited_context": "example",
        "source_artifact": "source.jsonl.gz",
        "source_line_number": str(index + 1),
    }


if __name__ == "__main__":
    unittest.main()
